stages:
  - test-repo
  - build
  - package
  - deploy

variables:
  IMAGE_TAG: frontend_$CI_COMMIT_SHORT_SHA
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  IMAGE_NAME: "true-shuffle"

Test Repository:
  image: node:21-alpine3.18
  stage: test-repo
  before_script:
    - npm cache clean --force
    - npm ci
  tags:
    - docker
  script:
    - npm test
  only:
    - basic-layout

Build:
  image: node:21-alpine3.18
  stage: build
  tags:
    - docker
  before_script:
    - npm cache clean --force
    - npm ci
  script:
    - npm run build
  only:
    - basic-layout

Package:
  image: docker:24.0.9
  stage: package
  tags:
    - docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:24.0.9-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
  only:
    - basic-layout

Deploy:
  stage: deploy
  tags:
    - bash
  script:
    - /scripts/deployFrontend.sh $DOCKER_USERNAME $DOCKER_PASSWORD $IMAGE_NAME $IMAGE_TAG
  only:
    - basic-layout